apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather 
spec:
  selector:
    matchLabels:
      greeting: weather 
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        greeting: weather 
        version: one
    spec:
      containers:
      - name: weather 
        image: "us-central1-docker.pkg.dev/ensign-421602/ensign-public/weather:extra"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: "PORT"
          value: "5555"
